version: '3.8'
services:
  client:
    build:
      context: .
    container_name: client-test
    ports:
      - '${CLIENT_PORT:-3000}:3000'
    env_file:
      - ./.env
    networks:
      - default

networks:
  default:
    driver: bridge
